In [1]:
from notebooks._utils import calculate_parallel_ensemble_accuracy
from notebooks._utils import calculate_baseline_accuracy, get_layers, calculate_oracle_accuracy


num_fewshots = 0
dataset_root = "/home/xzhao/workspace/GYB_self-ensemble/datasets"
all_models = ["pythia_2.8b", "llama3.2_3b", "qwen2.5_3b", "qwen3_4b", "qwen3_30b"]

In [2]:
ds_names = ["myriadlama", "hotpot"]

for ds_name in ds_names:
    for model_name in all_models:
        print(f"\n=================== Model: {model_name} ===================")
        dump_file_prefix = f"{dataset_root}/{ds_name}/{model_name}/{ds_name}."
        print("---- Calculating baseline ----")
        calculate_baseline_accuracy(dataset_root, ds_name, model_name, num_fewshots)
        
        print("---- Calculating Oracle ----")
        calculate_oracle_accuracy(dataset_root, ds_name, model_name, num_fewshots)
        
        print("---- Logits Ensemble + Layer Average ----")
        calculate_parallel_ensemble_accuracy(dump_file_prefix, repeat_paras=False,
            num_paraphrases=5, num_fewshots=num_fewshots, num_samples=5 if ds_name=="myriadlama" else 1,
            logits_ensemble_method="avg",
            ensemble_method="layer_output_avg",
            multilayer=True, ensemble_alpha=1.0, 
            ensemble_layer=get_layers(model_name),
            token_mode="last", use_generation=True)

=================== Model: pythia_2.8b ===================
---- Calculating baseline ----
Acc: 0.0781 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.3345 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.0957 ==> 🏷️ 5paras 0shots  layer_output_avg layer24 Multilayer alpha1.0 token-last

=================== Model: llama3.2_3b ===================
---- Calculating baseline ----
Acc: 0.3417 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.6815 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.4553 ==> 🏷️ 5paras 0shots  layer_output_avg layer21 Multilayer alpha1.0 token-last

=================== Model: qwen2.5_3b ===================
---- Calculating baseline ----
Acc: 0.1962 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.5540 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.3160 ==> 🏷️ 5paras 0shots  layer_output_avg layer27 Multilayer alpha1.0 token-last

=================== Model: qwen3_4b ===================
---- Calculating baseline ----
Acc: 0.2413 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.5560 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.3346 ==> 🏷️ 5paras 0shots  layer_output_avg layer27 Multilayer alpha1.0 token-last

=================== Model: qwen3_30b ===================
---- Calculating baseline ----
Acc: 0.3263 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.6465 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.4366 ==> 🏷️ 5paras 0shots  layer_output_avg layer36 Multilayer alpha1.0 token-last

=================== Model: pythia_2.8b ===================
---- Calculating baseline ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/hotpot/pythia_2.8b/baseline_per_prompt.0shots.feather'
---- Calculating Oracle ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/hotpot/pythia_2.8b/baseline_per_prompt.0shots.feather'
---- Logits Ensemble + Layer Average ----
File ./logits.avg.avglayer.layer24.alpha100.token-last.multilayer.0fshots.1samples.5paras.feather does not exist!

=================== Model: llama3.2_3b ===================
---- Calculating baseline ----
Acc: 0.0828 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.2190 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.2880 ==> 🏷️ 5paras 0shots  layer_output_avg layer21 Multilayer alpha1.0 token-last

=================== Model: qwen2.5_3b ===================
---- Calculating baseline ----
Acc: 0.1075 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.2050 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.2540 ==> 🏷️ 5paras 0shots  layer_output_avg layer27 Multilayer alpha1.0 token-last

=================== Model: qwen3_4b ===================
---- Calculating baseline ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/hotpot/qwen3_4b/baseline_per_prompt.0shots.feather'
---- Calculating Oracle ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/hotpot/qwen3_4b/baseline_per_prompt.0shots.feather'
---- Logits Ensemble + Layer Average ----
Acc: 0.1900 ==> 🏷️ 5paras 0shots  layer_output_avg layer27 Multilayer alpha1.0 token-last

=================== Model: qwen3_30b ===================
---- Calculating baseline ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/hotpot/qwen3_30b/baseline_per_prompt.0shots.feather'
---- Calculating Oracle ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/hotpot/qwen3_30b/baseline_per_prompt.0shots.feather'
---- Logits Ensemble + Layer Average ----
File ./logits.avg.avglayer.layer36.alpha100.token-last.multilayer.0fshots.1samples.5paras.feather does not exist!

In [3]:

for ds_name in ["commonsense", "mmlu", "logiqa"]:
# for ds_name in ["logiqa"]:
    print(f"\n=================== Dataset: {ds_name} ===================")
    num_fewshots = 0

    for model_name in all_models:
        print(f"\n---------- Model: {model_name} ----------")
        dump_file_prefix = f"{dataset_root}/{ds_name}_paraphrase/{model_name}/{ds_name}paraphrase."
        print("---- Calculating baseline ----")
        calculate_baseline_accuracy(dataset_root, ds_name, model_name, num_fewshots)
        
        print("---- Calculating Oracle ----")
        calculate_oracle_accuracy(dataset_root, ds_name, model_name, num_fewshots)
    
        print("---- Logits Ensemble + Layer Average ----")
        calculate_parallel_ensemble_accuracy(dump_file_prefix, repeat_paras=False,
            num_paraphrases=5, num_fewshots=num_fewshots, num_samples=1,
            logits_ensemble_method="avg",
            ensemble_method="layer_output_avg",
            multilayer=True, ensemble_alpha=1.0, 
            ensemble_layer=get_layers(model_name),
            token_mode="last", use_generation=True)

=================== Dataset: commonsense ===================

---------- Model: pythia_2.8b ----------
---- Calculating baseline ----
Acc: 0.1658 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.3560 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.0070 ==> 🏷️ 5paras 0shots  layer_output_avg layer24 Multilayer alpha1.0 token-last

---------- Model: llama3.2_3b ----------
---- Calculating baseline ----
Acc: 0.2105 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.4310 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.5020 ==> 🏷️ 5paras 0shots  layer_output_avg layer21 Multilayer alpha1.0 token-last

---------- Model: qwen2.5_3b ----------
---- Calculating baseline ----
Acc: 0.2178 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.6560 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.6510 ==> 🏷️ 5paras 0shots  layer_output_avg layer27 Multilayer alpha1.0 token-last

---------- Model: qwen3_4b ----------
---- Calculating baseline ----
Acc: 0.2054 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.5520 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.7410 ==> 🏷️ 5paras 0shots  layer_output_avg layer27 Multilayer alpha1.0 token-last

---------- Model: qwen3_30b ----------
---- Calculating baseline ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/commonsense_paraphrase/qwen3_30b/baseline_per_prompt.0shots.feather'
---- Calculating Oracle ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/commonsense_paraphrase/qwen3_30b/baseline_per_prompt.0shots.feather'
---- Logits Ensemble + Layer Average ----
File ./logits.avg.avglayer.layer36.alpha100.token-last.multilayer.0fshots.1samples.5paras.feather does not exist!

=================== Dataset: mmlu ===================

---------- Model: pythia_2.8b ----------
---- Calculating baseline ----
Acc: 0.2243 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.3900 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.0980 ==> 🏷️ 5paras 0shots  layer_output_avg layer24 Multilayer alpha1.0 token-last

---------- Model: llama3.2_3b ----------
---- Calculating baseline ----
Acc: 0.2107 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.4200 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.4170 ==> 🏷️ 5paras 0shots  layer_output_avg layer21 Multilayer alpha1.0 token-last

---------- Model: qwen2.5_3b ----------
---- Calculating baseline ----
Acc: 0.1972 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.5620 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.5450 ==> 🏷️ 5paras 0shots  layer_output_avg layer27 Multilayer alpha1.0 token-last

---------- Model: qwen3_4b ----------
---- Calculating baseline ----
Acc: 0.1342 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.3710 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.6540 ==> 🏷️ 5paras 0shots  layer_output_avg layer27 Multilayer alpha1.0 token-last

---------- Model: qwen3_30b ----------
---- Calculating baseline ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/mmlu_paraphrase/qwen3_30b/baseline_per_prompt.0shots.feather'
---- Calculating Oracle ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/mmlu_paraphrase/qwen3_30b/baseline_per_prompt.0shots.feather'
---- Logits Ensemble + Layer Average ----
File ./logits.avg.avglayer.layer36.alpha100.token-last.multilayer.0fshots.1samples.5paras.feather does not exist!

=================== Dataset: logiqa ===================

---------- Model: pythia_2.8b ----------
---- Calculating baseline ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/logiqa_paraphrase/pythia_2.8b/baseline_per_prompt.0shots.feather'
---- Calculating Oracle ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/logiqa_paraphrase/pythia_2.8b/baseline_per_prompt.0shots.feather'
---- Logits Ensemble + Layer Average ----
File ./logits.avg.avglayer.layer24.alpha100.token-last.multilayer.0fshots.1samples.5paras.feather does not exist!

---------- Model: llama3.2_3b ----------
---- Calculating baseline ----
Acc: 0.0580 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.1760 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.1210 ==> 🏷️ 5paras 0shots  layer_output_avg layer21 Multilayer alpha1.0 token-last

---------- Model: qwen2.5_3b ----------
---- Calculating baseline ----
Acc: 0.1653 ==> 🏷️ baseline of average accuracy per-paraphrase
---- Calculating Oracle ----
Acc: 0.4850 ==> 🏷️ Oracle accuracy per-paraphrase
---- Logits Ensemble + Layer Average ----
Acc: 0.3870 ==> 🏷️ 5paras 0shots  layer_output_avg layer27 Multilayer alpha1.0 token-last

---------- Model: qwen3_4b ----------
---- Calculating baseline ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/logiqa_paraphrase/qwen3_4b/baseline_per_prompt.0shots.feather'
---- Calculating Oracle ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/logiqa_paraphrase/qwen3_4b/baseline_per_prompt.0shots.feather'
---- Logits Ensemble + Layer Average ----
Acc: 0.6310 ==> 🏷️ 5paras 0shots  layer_output_avg layer27 Multilayer alpha1.0 token-last

---------- Model: qwen3_30b ----------
---- Calculating baseline ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/logiqa_paraphrase/qwen3_30b/baseline_per_prompt.0shots.feather'
---- Calculating Oracle ----
FileNotFoundError: [Errno 2] No such file or directory: '/home/xzhao/workspace/GYB_self-ensemble/datasets/logiqa_paraphrase/qwen3_30b/baseline_per_prompt.0shots.feather'
---- Logits Ensemble + Layer Average ----
File ./logits.avg.avglayer.layer36.alpha100.token-last.multilayer.0fshots.1samples.5paras.feather does not exist!

In [ ]:
import pandas as pd
# filename = "/home/xzhao/workspace/GYB_self-ensemble/datasets/mmlu-debug/llama3.2_1b/baseline_per_prompt.0shots.feather"
filename = "/home/xzhao/workspace/GYB_self-ensemble/datasets/mmlu-debug/llama3.2_1b/mmluparaphrase.ppl.baseline.5paras.feather"

In [50]:
df = pd.read_feather(filename) 
df.shape

(505, 14)

In [51]:
df[df['uuid'] == df['uuid'].tolist()[0]]

,uuid,answers,prediction,generation,correctness,qonly_prompts,qchoice_prompts,paraphrases,is_origs,ppls,best_choice_idx,choices_label,choices_text,answer_label
0,000d45b3136678e85a763c55a797fe44,C,B,B,None,[You are given a multiple-choice question.\nCh...,[You are given a multiple-choice question.\nCh...,[Given the velocity function v(t) = t cos(t) -...,[False],"[7368.35791015625, 2685.010986328125, 2833.930...",one,"[A, B, C, D]","[none, one, two, three]",C
1,000d45b3136678e85a763c55a797fe44,C,B,B,None,[You are given a multiple-choice question.\nCh...,[You are given a multiple-choice question.\nCh...,"[Over t between 0 and 10, how often does the m...",[False],"[9063.3037109375, 3968.18896484375, 4172.82470...",one,"[A, B, C, D]","[none, one, two, three]",C
2,000d45b3136678e85a763c55a797fe44,C,B,B,None,[You are given a multiple-choice question.\nCh...,[You are given a multiple-choice question.\nCh...,[How many times does the particle change its d...,[False],"[6789.2216796875, 2802.295654296875, 2881.6213...",one,"[A, B, C, D]","[none, one, two, three]",C
3,000d45b3136678e85a763c55a797fe44,C,C,C,None,[You are given a multiple-choice question.\nCh...,[You are given a multiple-choice question.\nCh...,[An object moving along a line has velocity v(...,[True],"[7102.21630859375, 2819.468017578125, 2771.127...",two,"[A, B, C, D]","[none, one, two, three]",C
4,000d45b3136678e85a763c55a797fe44,C,C,C,None,[You are given a multiple-choice question.\nCh...,[You are given a multiple-choice question.\nCh...,[For 0 ≤ t ≤ 10 with velocity v(t) = t cos(t) ...,[False],"[6953.10009765625, 3066.551513671875, 3043.964...",two,"[A, B, C, D]","[none, one, two, three]",C

In [45]:
df

,uuid,answers,paraphrase,prompt,prediction,generation,is_orig,predict_lemma,generation_lemmas,answer_lemmas
0,5a7a06935542990198eaf050,[Arthur's Magazine],Which magazine was started first Arthur's Maga...,Answer the question based on the provided cont...,Arthur's First for Women's First for Women's F...,Arthur's First for Women's First for Women's F...,True,"[arthur, 's, first, for, women, 's, first, for...","[arthur, 's, first, for, women, 's, first, for...","[[arthur, 's, magazine]]"
1,5a879ab05542996e4f30887e,[Delhi],The Oberoi family is part of a hotel company t...,Answer the question based on the provided cont...,"New Delhi, Mumbai, Mumbai, Mumbai, Mumbai, Mum...","New Delhi, Mumbai, Mumbai, Mumbai, Mumbai, Mum...",True,"[new, delhi, ,, mumbai, ,, mumbai, ,, mumbai, ...","[new, delhi, ,, mumbai, ,, mumbai, ,, mumbai, ...",[[delhi]]
2,5a8d7341554299441c6b9fe5,[President Richard Nixon],Musician and satirist Allie Goertz wrote a son...,Answer the question based on the provided cont...,Milhouse,"Milhouse\n\nQ: ""The Simpsons'Allie.\n\nB:",True,[milhouse],"[milhouse, \n\n, q, :, "", the, simpsons'allie]","[[president, richard, nixon]]"
3,5a82171f5542990a1d231f4a,[American],What nationality was James Henry Miller's wife?,Answer the question based on the provided cont...,James Henry Miller was a.,James Henry Miller was a.\n\n\n\nB:,True,"[james, henry, miller, be, a.]","[james, henry, miller, be, a]",[[american]]
4,5a84dd955542997b5ce3ff79,[alcohol],Cadmium Chloride is slightly soluble in this c...,Answer the question based on the provided cont...,Cadmium chloride,Cadmium chloride\n\n\nQ: A: a.\nQ: Cadmium\nQ:,True,"[cadmium, chloride]","[cadmium, chloride, \n\n\n, q, :, a, :, a]",[[alcohol]]
...,...,...,...,...,...,...,...,...,...,...
500,5a8f938a55429918e830d275,[17%],Approximately what share of the world populati...,Answer the question based on the provided cont...,The ethnic group B:,The ethnic group B: \n\n\n\nB,False,"[the, ethnic, group, b, :, ]","[the, ethnic, group, b, :, \n\n\n\n, b]","[[17, %]]"
501,5add3b665542997545bbbcd2,[David Lyle Boren],"Who, as an Oklahoma politician, was partly beh...",Answer the question based on the provided cont...,The Boren Boren Boren Boren Boren Boren Boren ...,The Boren Boren Boren Boren Boren Boren Boren ...,False,"[the, boren, boren, boren, boren, boren, boren...","[the, boren, boren, boren, boren, boren, boren...","[[david, lyle, boren]]"
502,5ab728e45542992aa3b8c7b4,[Lawrence County],Which county contains the museum where the Tho...,Answer the question based on the provided cont...,The county of the county of the county of the,The county of the county of the county of the\...,False,"[the, county, of, the, county, of, the, county...","[the, county, of, the, county, of, the, county...","[[lawrence, county]]"
503,5a74fbe55542996c70cfae63,[MedStar Washington Hospital Center],Which of these two hospitals is the biggest pr...,Answer the question based on the provided cont...,Children's MedStar is the MedStar is the MedSt...,Children's MedStar is the MedStar is the MedSt...,False,"[children, 's, medstar, be, the, medstar, be, ...","[children, 's, medstar, be, the, medstar, be, ...","[[medstar, washington, hospital, center]]"
504,5ab30bbb55429976abd1bc39,[Great Britain],"Prince William, Duke of Gloucester and Prince ...",Answer the question based on the provided cont...,Denmark,Denmark\n\nB: Denmark\n\n\n\nB:,False,[denmark],"[denmark, \n\n, b, :, denmark, \n\n\n\n, b, :]","[[great, britain]]"