In [86]:
import pandas
from utils import partial_match_scores

dataset_root = "/home/xzhao/workspace/GYB_self-ensemble/datasets"
ds_name = "myriadlama"
model_name = "llama3.2_3b_it"

def get_filenames(modifyattn, modifyrope, repeat_paras, single_para_qapair, num_paraphrases, num_samples=5):
    dump_file = f"{dataset_root}/{ds_name}/{model_name}/myriadlama."
    if modifyattn:
        dump_file += "modifyattn."
    if modifyrope:
        dump_file += "modifyrope."
    if repeat_paras:
        dump_file += "repeatparas."
    if single_para_qapair:
        dump_file += "singleparaqapair."


    dump_file += f"{num_samples}samples.{num_paraphrases}paras.feather"
    # print(f"Loading from {dump_file}")
    return dump_file

def _calculate_accuracy(df, label):
    predicts = [[pred] for pred in df["predict_lemma"].tolist()]
    answers = [answers for answers in df["answer_lemmas"]]
    acc = partial_match_scores(predicts, answers, birdirect=True)    
    print(f"{label} Accuracy: {acc:.4f}")

def calculate_accuracy(modifyattn, modifyrope, repeat_paras, single_para_qapair, num_paraphrases, num_samples=5):
    filename = get_filenames(modifyattn, modifyrope, repeat_paras, single_para_qapair, num_paraphrases, num_samples=num_samples)
    df = pandas.read_feather(filename)
    label = f"MyriadLlama {'+Attn' if modifyattn else ''} {'+Rope' if modifyrope else ''} {'+RepeatParas' if repeat_paras else ''} {num_paraphrases} Paras"
    _calculate_accuracy(df, label)
    return df

baseline_fn = f"{dataset_root}/{ds_name}/{model_name}/baseline_origin.feather"
baseline2_fn = f"{dataset_root}/{ds_name}/{model_name}/baseline_per_prompt.feather"

In [ ]:
baseline = pandas.read_feather(baseline2_fn)
baseline["predict_lemma"] = baseline["predict_lemma"].apply(lambda xs: xs[0])
_calculate_accuracy(baseline, "MyriadLlama Baseline Per Prompt")

MyriadLlama Baseline Per Prompt Accuracy: 0.4105

In [90]:
print("=== No attention or rope modifications, with separated QA section for different paraphrases ===")
para2 = calculate_accuracy(modifyattn=False, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=2)
para3 = calculate_accuracy(modifyattn=False, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=3)
para4 = calculate_accuracy(modifyattn=False, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=4)
para5 = calculate_accuracy(modifyattn=False, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=5)

=== No attention or rope modifications, with separated QA section for different paraphrases ===
MyriadLlama    2 Paras Accuracy: 0.4396
MyriadLlama    3 Paras Accuracy: 0.4607
MyriadLlama    4 Paras Accuracy: 0.4694
MyriadLlama    5 Paras Accuracy: 0.4724

In [33]:
print("=== No attention or rope modifications, with single QA section for concatnated paraphrases ===")
para2 = calculate_accuracy(modifyattn=False, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=2)
para3 = calculate_accuracy(modifyattn=False, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=3)
para4 = calculate_accuracy(modifyattn=False, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=4)
para5 = calculate_accuracy(modifyattn=False, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=5)

=== No attention or rope modifications, with single QA section for concatnated paraphrases ===
MyriadLlama    2 Paras Accuracy: 0.4217
MyriadLlama    3 Paras Accuracy: 0.4300
MyriadLlama    4 Paras Accuracy: 0.4360
MyriadLlama    5 Paras Accuracy: 0.4456

In [34]:
print("=== With only attention modifications, with single QA section for concatnated paraphrases ===")
para2 = calculate_accuracy(modifyattn=True, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=2)
para3 = calculate_accuracy(modifyattn=True, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=3)
para4 = calculate_accuracy(modifyattn=True, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=4)
para5 = calculate_accuracy(modifyattn=True, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=5)

=== With only attention modifications, with single QA section for concatnated paraphrases ===
MyriadLlama +Attn   2 Paras Accuracy: 0.4368
MyriadLlama +Attn   3 Paras Accuracy: 0.4428
MyriadLlama +Attn   4 Paras Accuracy: 0.4490
MyriadLlama +Attn   5 Paras Accuracy: 0.4468

In [35]:
print("=== With only attention modifications, with separated QA section for different paraphrases ===")
para2 = calculate_accuracy(modifyattn=True, modifyrope=False, repeat_paras=False, single_para_qapair=False, num_paraphrases=2)
para3 = calculate_accuracy(modifyattn=True, modifyrope=False, repeat_paras=False, single_para_qapair=False, num_paraphrases=3)
para4 = calculate_accuracy(modifyattn=True, modifyrope=False, repeat_paras=False, single_para_qapair=False, num_paraphrases=4)
para5 = calculate_accuracy(modifyattn=True, modifyrope=False, repeat_paras=False, single_para_qapair=False, num_paraphrases=5)

=== With only attention modifications, with separated QA section for different paraphrases ===
MyriadLlama +Attn   2 Paras Accuracy: 0.4090
MyriadLlama +Attn   3 Paras Accuracy: 0.4194
MyriadLlama +Attn   4 Paras Accuracy: 0.4238
MyriadLlama +Attn   5 Paras Accuracy: 0.4292

In [44]:
print("=== With only attention modifications, with single QA section for concatnated paraphrases ===")
para2 = calculate_accuracy(modifyattn=True, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=2)
para3 = calculate_accuracy(modifyattn=True, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=3)
para4 = calculate_accuracy(modifyattn=True, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=4)
para5 = calculate_accuracy(modifyattn=True, modifyrope=False, repeat_paras=False, single_para_qapair=True, num_paraphrases=5)

=== With only attention modifications, with single QA section for concatnated paraphrases ===
MyriadLlama +Attn   2 Paras Accuracy: 0.4368
MyriadLlama +Attn   3 Paras Accuracy: 0.4428
MyriadLlama +Attn   4 Paras Accuracy: 0.4490
MyriadLlama +Attn   5 Paras Accuracy: 0.4468

In [38]:
answers = [answers.tolist() for answers in baseline["answers"].tolist()]
# prompts = baseline['question'].tolist()
base = baseline['prediction'].tolist()
pred2 = para2['prediction'].tolist()
pred3 = para3['prediction'].tolist()
pred4 = para4['prediction'].tolist()
pred5 = para5['prediction'].tolist()

In [84]:
import pandas as pd
df = pd.read_feather("/home/xzhao/workspace/GYB_self-ensemble/datasets/myriadlama-debug/llama3.2_1b_it/myriadlama.modifyattn.modifyrope.singleparaqapair.5samples.3paras.feather")
df.head(1)

,uuid,answers,prediction,generation,templates,prompt,paraphrases,predict_lemma,answer_lemmas
0,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",BBC,BBC,[[This Is Your Life premiered on the network [...,"Based on the context, predict the [MASK] in th...",[This Is Your Life premiered on the network [M...,bbc,"[[nbc], [national, broadcasting, company]]"

In [85]:
print(df["prompt"].tolist()[0])

Based on the context, predict the [MASK] in the sentence in one word.

Q: Belo Horizonte and [MASK] are twin cities.
A: Lisbon

Q: Hotel Green is located in [MASK].
A: Pasadena

Q: Typekit was a product announced by [MASK].
A: Adobe

Q: The operation of GIC Private Limited depends on the headquarters in [MASK].
A: Singapore

Q: Duke Ellington is represented by music label [MASK].
A: Decca

Q: This Is Your Life premiered on the network [MASK].
[MASK] is the first air channel of This Is Your Life.
This Is Your Life was initially launched on [MASK].
A:

In [79]:
df["answer_lemmas"] = df["answer_lemmas"].apply(lambda xs: [list(x) for x in xs])
df

,uuid,answers,prediction,generation,templates,prompt,paraphrases,predict_lemma,answer_lemmas
0,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",BBC,BBC,[[This Is Your Life premiered on the network [...,"Based on the context, predict the [MASK] in th...",[This Is Your Life premiered on the network [M...,bbc,"[[nbc], [national, broadcasting, company]]"
1,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",CBS,CBS,[[Which service originally aired This Is Your ...,"Based on the context, predict the [MASK] in th...",[Which service originally aired This Is Your L...,cbs,"[[nbc], [national, broadcasting, company]]"
2,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",CBS,CBS,[[This Is Your Life was initially shown on [MA...,"Based on the context, predict the [MASK] in th...",[This Is Your Life was initially shown on [MAS...,cbs,"[[nbc], [national, broadcasting, company]]"
3,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",CBS,CBS,[[[MASK] had the distinction of being the firs...,"Based on the context, predict the [MASK] in th...",[[MASK] had the distinction of being the first...,cbs,"[[nbc], [national, broadcasting, company]]"
4,5d09424876ba7f4-15e8746c51e1d4c,"[NBC, National Broadcasting Company]",CBS,CBS,[[This Is Your Life was first unveiled on [MAS...,"Based on the context, predict the [MASK] in th...",[This Is Your Life was first unveiled on [MASK...,cbs,"[[nbc], [national, broadcasting, company]]"
...,...,...,...,...,...,...,...,...,...
95,04dc00943c6cc89-e962371af6d24da,"[piano, pianoforte, concert grand piano, forte...",keyboard,keyboard,"[[George Duke is a [MASK] player., George Duke...","Based on the context, predict the [MASK] in th...","[George Duke is a [MASK] player., George Duke ...",keyboard,"[[piano], [pianoforte], [concert, grand, piano..."
96,04dc00943c6cc89-e962371af6d24da,"[piano, pianoforte, concert grand piano, forte...",jazz,jazz,[[George Duke became known as a [MASK] player....,"Based on the context, predict the [MASK] in th...","[George Duke became known as a [MASK] player.,...",jazz,"[[piano], [pianoforte], [concert, grand, piano..."
97,04dc00943c6cc89-e962371af6d24da,"[piano, pianoforte, concert grand piano, forte...",jazz,jazz,[[George Duke is an accomplished [MASK] artist...,"Based on the context, predict the [MASK] in th...",[George Duke is an accomplished [MASK] artist....,jazz,"[[piano], [pianoforte], [concert, grand, piano..."
98,04dc00943c6cc89-e962371af6d24da,"[piano, pianoforte, concert grand piano, forte...",Piano,Piano,[[What musical instrument does George Duke pla...,"Based on the context, predict the [MASK] in th...",[What musical instrument does George Duke play...,piano,"[[piano], [pianoforte], [concert, grand, piano..."
99,04dc00943c6cc89-e962371af6d24da,"[piano, pianoforte, concert grand piano, forte...",keyboardist,keyboardist,[[George Duke was identified as a talented [MA...,"Based on the context, predict the [MASK] in th...",[George Duke was identified as a talented [MAS...,keyboardist,"[[piano], [pianoforte], [concert, grand, piano..."

0.27

In [82]:
predicts = df["generation"].tolist()
answers = [answers for answers in df["answers"]]
partial_match_scores(predicts, answers, birdirect=True)

0.2

In [41]:
for ans, p0, p2, p3, p4, p5 in zip(answers, base, pred2, pred3, pred4, pred5):
    print("===")
    # print("Prompt:", prompt)
    print("Answers:", ans)
    print("Baseline Prediction:", p0)
    print("Two Paraphrases Prediction:", p2)
    print("Three Paraphrases Prediction:", p3)
    print("Four Paraphrases Prediction:", p4)
    print("Five Paraphrases Prediction:", p5)
    print()

===
Answers: ['NBC', 'National Broadcasting Company']
Baseline Prediction: NBC
Two Paraphrases Prediction: ABC
Three Paraphrases Prediction: 1952
Four Paraphrases Prediction: 1952
Five Paraphrases Prediction: Ed

===
Answers: ['physics', 'physical', 'physic', 'general physics', 'physical science']
Baseline Prediction: optics
Two Paraphrases Prediction: March
Three Paraphrases Prediction: Ed
Four Paraphrases Prediction: ABC
Five Paraphrases Prediction: May

===
Answers: ['Norwegian', 'no', 'Norwegian language']
Baseline Prediction: Norwegian
Two Paraphrases Prediction: Ed
Three Paraphrases Prediction: ABC
Four Paraphrases Prediction: ABC
Five Paraphrases Prediction: ABC

===
Answers: ['Florence', 'Firenze', 'Florence, Italy', 'Florence, Tuscany', 'Florencia', 'Florentia', 'Florenz', 'Firenca', 'Florencie', 'Fiuränza', 'Florentzia', 'Firense', 'Firenz', 'Firenzi', 'Florence Municipality']
Baseline Prediction: Florence
Two Paraphrases Prediction: 1952
Three Paraphrases Prediction: 1952
Four Paraphrases Prediction: ABC
Five Paraphrases Prediction: ABC

===
Answers: ['Antarctica', 'Antarctic Selection']
Baseline Prediction: Antarctica
Two Paraphrases Prediction: March
Three Paraphrases Prediction: ABC
Four Paraphrases Prediction: ABC
Five Paraphrases Prediction: NBC

===
Answers: ['Turin', 'Torino', 'Turin, Italy']
Baseline Prediction: Italy
Two Paraphrases Prediction: optics
Three Paraphrases Prediction: optics
Four Paraphrases Prediction: optics
Five Paraphrases Prediction: optics

===
Answers: ['bishop']
Baseline Prediction: mayor
Two Paraphrases Prediction: optics
Three Paraphrases Prediction: astronomy
Four Paraphrases Prediction: optics
Five Paraphrases Prediction: optics

===
Answers: ['Boston', 'Boston, Lincolnshire', 'Boston, England']
Baseline Prediction: England
Two Paraphrases Prediction: optics
Three Paraphrases Prediction: astronomy
Four Paraphrases Prediction: optics
Five Paraphrases Prediction: physics

===
Answers: ['NBC', 'National Broadcasting Company']
Baseline Prediction: WOR
Two Paraphrases Prediction: optics
Three Paraphrases Prediction: optics
Four Paraphrases Prediction: physics
Five Paraphrases Prediction: optics

===
Answers: ['physics', 'physical', 'physic', 'general physics', 'physical science']
Baseline Prediction: optics
Two Paraphrases Prediction: physics
Three Paraphrases Prediction: optics
Four Paraphrases Prediction: optics
Five Paraphrases Prediction: physics

===
Answers: ['Norwegian', 'no', 'Norwegian language']
Baseline Prediction: Old Norse
Two Paraphrases Prediction: runes
Three Paraphrases Prediction: Danish
Four Paraphrases Prediction: Danish
Five Paraphrases Prediction: runes

===
Answers: ['Florence', 'Firenze', 'Florence, Italy', 'Florence, Tuscany', 'Florencia', 'Florentia', 'Florenz', 'Firenca', 'Florencie', 'Fiuränza', 'Florentzia', 'Firense', 'Firenz', 'Firenzi', 'Florence Municipality']
Baseline Prediction: Florence
Two Paraphrases Prediction: Danish
Three Paraphrases Prediction: Danish
Four Paraphrases Prediction: Denmark
Five Paraphrases Prediction: Danish

===
Answers: ['Antarctica', 'Antarctic Selection']
Baseline Prediction: Antarctic
Two Paraphrases Prediction: Danish
Three Paraphrases Prediction: Danish
Four Paraphrases Prediction: Old
Five Paraphrases Prediction: Danish

===
Answers: ['Turin', 'Torino', 'Turin, Italy']
Baseline Prediction: Italy
Two Paraphrases Prediction: fantasy
Three Paraphrases Prediction: Danish
Four Paraphrases Prediction: Danish
Five Paraphrases Prediction: Danish

===
Answers: ['bishop']
Baseline Prediction: mayor
Two Paraphrases Prediction: Danish
Three Paraphrases Prediction: Danish
Four Paraphrases Prediction: Danish
Five Paraphrases Prediction: Danish

===
Answers: ['Boston', 'Boston, Lincolnshire', 'Boston, England']
Baseline Prediction: England
Two Paraphrases Prediction: Florence
Three Paraphrases Prediction: Venice
Four Paraphrases Prediction: Florence
Five Paraphrases Prediction: Padua

===
Answers: ['NBC', 'National Broadcasting Company']
Baseline Prediction: NBC
Two Paraphrases Prediction: Venice
Three Paraphrases Prediction: Florence
Four Paraphrases Prediction: Venice
Five Paraphrases Prediction: Venice

===
Answers: ['physics', 'physical', 'physic', 'general physics', 'physical science']
Baseline Prediction: optics
Two Paraphrases Prediction: Florence
Three Paraphrases Prediction: 1563
Four Paraphrases Prediction: 1563
Five Paraphrases Prediction: 1563

===
Answers: ['Norwegian', 'no', 'Norwegian language']
Baseline Prediction: Danish
Two Paraphrases Prediction: Venice
Three Paraphrases Prediction: Florence
Four Paraphrases Prediction: Venice
Five Paraphrases Prediction: Venice

===
Answers: ['Florence', 'Firenze', 'Florence, Italy', 'Florence, Tuscany', 'Florencia', 'Florentia', 'Florenz', 'Firenca', 'Florencie', 'Fiuränza', 'Florentzia', 'Firense', 'Firenz', 'Firenzi', 'Florence Municipality']
Baseline Prediction: Florence
Two Paraphrases Prediction: Padua
Three Paraphrases Prediction: Venice
Four Paraphrases Prediction: Florence
Five Paraphrases Prediction: 1563

===
Answers: ['Antarctica', 'Antarctic Selection']
Baseline Prediction: Antarctica
Two Paraphrases Prediction: Antarctica
Three Paraphrases Prediction: Antarctica
Four Paraphrases Prediction: Antarctica
Five Paraphrases Prediction: Antarctic

===
Answers: ['Turin', 'Torino', 'Turin, Italy']
Baseline Prediction: Florence
Two Paraphrases Prediction: Antarctica
Three Paraphrases Prediction: Antarctic
Four Paraphrases Prediction: Antarctica
Five Paraphrases Prediction: Antarctic

===
Answers: ['bishop']
Baseline Prediction: mayor
Two Paraphrases Prediction: Antarctica
Three Paraphrases Prediction: Antarctic
Four Paraphrases Prediction: Antarctica
Five Paraphrases Prediction: Antarctica

===
Answers: ['Boston', 'Boston, Lincolnshire', 'Boston, England']
Baseline Prediction: war
Two Paraphrases Prediction: Antarctica
Three Paraphrases Prediction: Antarctica
Four Paraphrases Prediction: Antarctic
Five Paraphrases Prediction: Antarctica

===
Answers: ['NBC', 'National Broadcasting Company']
Baseline Prediction: ABC
Two Paraphrases Prediction: Antarctica
Three Paraphrases Prediction: Antarctica
Four Paraphrases Prediction: Antarctic
Five Paraphrases Prediction: Antarctica

===
Answers: ['physics', 'physical', 'physic', 'general physics', 'physical science']
Baseline Prediction: optics
Two Paraphrases Prediction: 1881
Three Paraphrases Prediction: Italy
Four Paraphrases Prediction: Italy
Five Paraphrases Prediction: 1908

===
Answers: ['Norwegian', 'no', 'Norwegian language']
Baseline Prediction: Danish
Two Paraphrases Prediction: Italy
Three Paraphrases Prediction: 1881
Four Paraphrases Prediction: 1881
Five Paraphrases Prediction: 1880

===
Answers: ['Florence', 'Firenze', 'Florence, Italy', 'Florence, Tuscany', 'Florencia', 'Florentia', 'Florenz', 'Firenca', 'Florencie', 'Fiuränza', 'Florentzia', 'Firense', 'Firenz', 'Firenzi', 'Florence Municipality']
Baseline Prediction: 1563
Two Paraphrases Prediction: Italy
Three Paraphrases Prediction: 1907
Four Paraphrases Prediction: Italy
Five Paraphrases Prediction: space

===
Answers: ['Antarctica', 'Antarctic Selection']
Baseline Prediction: Antarctica
Two Paraphrases Prediction: Italy
Three Paraphrases Prediction: Italy
Four Paraphrases Prediction: Genoa
Five Paraphrases Prediction: Italy

===
Answers: ['Turin', 'Torino', 'Turin, Italy']
Baseline Prediction: Italy
Two Paraphrases Prediction: Italy
Three Paraphrases Prediction: 1908
Four Paraphrases Prediction: Italy
Five Paraphrases Prediction: 1908

===
Answers: ['bishop']
Baseline Prediction: center
Two Paraphrases Prediction: Minister
Three Paraphrases Prediction: midfielder
Four Paraphrases Prediction: mayor
Five Paraphrases Prediction: actor

===
Answers: ['Boston', 'Boston, Lincolnshire', 'Boston, England']
Baseline Prediction: England
Two Paraphrases Prediction: midfielder
Three Paraphrases Prediction: mayor
Four Paraphrases Prediction: engineer
Five Paraphrases Prediction: actor

===
Answers: ['NBC', 'National Broadcasting Company']
Baseline Prediction: ABC
Two Paraphrases Prediction: bishop
Three Paraphrases Prediction: midfielder
Four Paraphrases Prediction: mayor
Five Paraphrases Prediction: actor

===
Answers: ['physics', 'physical', 'physic', 'general physics', 'physical science']
Baseline Prediction: optics
Two Paraphrases Prediction: Minister
Three Paraphrases Prediction: actor
Four Paraphrases Prediction: Minister
Five Paraphrases Prediction: mayor

===
Answers: ['Norwegian', 'no', 'Norwegian language']
Baseline Prediction: Danish
Two Paraphrases Prediction: engineer
Three Paraphrases Prediction: midfielder
Four Paraphrases Prediction: actor
Five Paraphrases Prediction: engineer

===
Answers: ['Florence', 'Firenze', 'Florence, Italy', 'Florence, Tuscany', 'Florencia', 'Florentia', 'Florenz', 'Firenca', 'Florencie', 'Fiuränza', 'Florentzia', 'Firense', 'Firenz', 'Firenzi', 'Florence Municipality']
Baseline Prediction: Padua
Two Paraphrases Prediction: prominence
Three Paraphrases Prediction: war
Four Paraphrases Prediction: England
Five Paraphrases Prediction: school

===
Answers: ['Antarctica', 'Antarctic Selection']
Baseline Prediction: Antarctica
Two Paraphrases Prediction: 1943
Three Paraphrases Prediction: England
Four Paraphrases Prediction: war
Five Paraphrases Prediction: academia

===
Answers: ['Turin', 'Torino', 'Turin, Italy']
Baseline Prediction: 1881
Two Paraphrases Prediction: prominence
Three Paraphrases Prediction: 1940
Four Paraphrases Prediction: war
Five Paraphrases Prediction: England

===
Answers: ['bishop']
Baseline Prediction: director
Two Paraphrases Prediction: 1940
Three Paraphrases Prediction: England
Four Paraphrases Prediction: England
Five Paraphrases Prediction: London

===
Answers: ['Boston', 'Boston, Lincolnshire', 'Boston, England']
Baseline Prediction: 1942
Two Paraphrases Prediction: 1960
Three Paraphrases Prediction: England
Four Paraphrases Prediction: England
Five Paraphrases Prediction: England

===
Answers: ['NBC', 'National Broadcasting Company']
Baseline Prediction: 1952
Two Paraphrases Prediction: Norway
Three Paraphrases Prediction: Norway
Four Paraphrases Prediction: Norway
Five Paraphrases Prediction: Norway

===
Answers: ['physics', 'physical', 'physic', 'general physics', 'physical science']
Baseline Prediction: optics
Two Paraphrases Prediction: Norway
Three Paraphrases Prediction: Norway
Four Paraphrases Prediction: Norway
Five Paraphrases Prediction: Norway

===
Answers: ['Norwegian', 'no', 'Norwegian language']
Baseline Prediction: text
Two Paraphrases Prediction: Oslo
Three Paraphrases Prediction: Norway
Four Paraphrases Prediction: Norway
Five Paraphrases Prediction: Norway

===
Answers: ['Florence', 'Firenze', 'Florence, Italy', 'Florence, Tuscany', 'Florencia', 'Florentia', 'Florenz', 'Firenca', 'Florencie', 'Fiuränza', 'Florentzia', 'Firense', 'Firenz', 'Firenzi', 'Florence Municipality']
Baseline Prediction: Florence
Two Paraphrases Prediction: Norway
Three Paraphrases Prediction: Norway
Four Paraphrases Prediction: 1904
Five Paraphrases Prediction: 1904

===
Answers: ['Antarctica', 'Antarctic Selection']
Baseline Prediction: Antarctica
Two Paraphrases Prediction: Norway
Three Paraphrases Prediction: Norway
Four Paraphrases Prediction: 1867
Five Paraphrases Prediction: Norway

===
Answers: ['Turin', 'Torino', 'Turin, Italy']
Baseline Prediction: Italy
Two Paraphrases Prediction: South
Three Paraphrases Prediction: South
Four Paraphrases Prediction: Africa
Five Paraphrases Prediction: Belgium

===
Answers: ['bishop']
Baseline Prediction: bishop
Two Paraphrases Prediction: Belgium
Three Paraphrases Prediction: Africa
Four Paraphrases Prediction: Burundi
Five Paraphrases Prediction: Burundi

===
Answers: ['Boston', 'Boston, Lincolnshire', 'Boston, England']
Baseline Prediction: 1940
Two Paraphrases Prediction: Africa
Three Paraphrases Prediction: Belgium
Four Paraphrases Prediction: United
Five Paraphrases Prediction: Burundi

===
Answers: ['NBC', 'National Broadcasting Company']
Baseline Prediction: NBC
Two Paraphrases Prediction: Belgium
Three Paraphrases Prediction: Belgium
Four Paraphrases Prediction: Burundi
Five Paraphrases Prediction: Belgium

===
Answers: ['physics', 'physical', 'physic', 'general physics', 'physical science']
Baseline Prediction: optics
Two Paraphrases Prediction: Commonwealth
Three Paraphrases Prediction: Burundi
Four Paraphrases Prediction: Burundi
Five Paraphrases Prediction: Belgium

===
Answers: ['Norwegian', 'no', 'Norwegian language']
Baseline Prediction: Denmark
Two Paraphrases Prediction: Vienna
Three Paraphrases Prediction: Regensburg
Four Paraphrases Prediction: Regensburg
Five Paraphrases Prediction: Vienna

===
Answers: ['Florence', 'Firenze', 'Florence, Italy', 'Florence, Tuscany', 'Florencia', 'Florentia', 'Florenz', 'Firenca', 'Florencie', 'Fiuränza', 'Florentzia', 'Firense', 'Firenz', 'Firenzi', 'Florence Municipality']
Baseline Prediction: Florence
Two Paraphrases Prediction: Vienna
Three Paraphrases Prediction: Vienna
Four Paraphrases Prediction: Regensburg
Five Paraphrases Prediction: Vienna

===
Answers: ['Antarctica', 'Antarctic Selection']
Baseline Prediction: Antarctica
Two Paraphrases Prediction: Vienna
Three Paraphrases Prediction: Vienna
Four Paraphrases Prediction: Vienna
Five Paraphrases Prediction: Vienna

===
Answers: ['Turin', 'Torino', 'Turin, Italy']
Baseline Prediction: Italy
Two Paraphrases Prediction: Vienna
Three Paraphrases Prediction: Vienna
Four Paraphrases Prediction: Vienna
Five Paraphrases Prediction: Vienna

===
Answers: ['bishop']
Baseline Prediction: engineer
Two Paraphrases Prediction: Vienna
Three Paraphrases Prediction: Vienna
Four Paraphrases Prediction: Nuremberg
Five Paraphrases Prediction: Vienna

===
Answers: ['Boston', 'Boston, Lincolnshire', 'Boston, England']
Baseline Prediction: England
Two Paraphrases Prediction: 1998
Three Paraphrases Prediction: Teledyaryo
Four Paraphrases Prediction: 1990
Five Paraphrases Prediction: Philippines

===
Answers: ['NBC', 'National Broadcasting Company']
Baseline Prediction: television
Two Paraphrases Prediction: 1990
Three Paraphrases Prediction: Philippines
Four Paraphrases Prediction: Philippines
Five Paraphrases Prediction: Philippines

===
Answers: ['physics', 'physical', 'physic', 'general physics', 'physical science']
Baseline Prediction: optics
Two Paraphrases Prediction: Philippines
Three Paraphrases Prediction: 1998
Four Paraphrases Prediction: Philippines
Five Paraphrases Prediction: Philippines

===
Answers: ['Norwegian', 'no', 'Norwegian language']
Baseline Prediction: fantasy
Two Paraphrases Prediction: Baguio
Three Paraphrases Prediction: 1998
Four Paraphrases Prediction: 1998
Five Paraphrases Prediction: Manila

===
Answers: ['Florence', 'Firenze', 'Florence, Italy', 'Florence, Tuscany', 'Florencia', 'Florentia', 'Florenz', 'Firenca', 'Florencie', 'Fiuränza', 'Florentzia', 'Firense', 'Firenz', 'Firenzi', 'Florence Municipality']
Baseline Prediction: Florence
Two Paraphrases Prediction: Philippines
Three Paraphrases Prediction: Philippines
Four Paraphrases Prediction: Teledyaryo
Five Paraphrases Prediction: Manila

===
Answers: ['Antarctica', 'Antarctic Selection']
Baseline Prediction: Antarctica
Two Paraphrases Prediction: striker
Three Paraphrases Prediction: fullback
Four Paraphrases Prediction: stand-up
Five Paraphrases Prediction: cricketer

===
Answers: ['Turin', 'Torino', 'Turin, Italy']
Baseline Prediction: 1906
Two Paraphrases Prediction: stand-up
Three Paraphrases Prediction: maintenance
Four Paraphrases Prediction: drums
Five Paraphrases Prediction: midfielder

===
Answers: ['bishop']
Baseline Prediction: engineer
Two Paraphrases Prediction: maintenance
Three Paraphrases Prediction: fullback
Four Paraphrases Prediction: vocals
Five Paraphrases Prediction: maintenance

===
Answers: ['Boston', 'Boston, Lincolnshire', 'Boston, England']
Baseline Prediction: prominence
Two Paraphrases Prediction: midfielder
Three Paraphrases Prediction: striker
Four Paraphrases Prediction: comedian
Five Paraphrases Prediction: fullback

===
Answers: ['NBC', 'National Broadcasting Company']
Baseline Prediction: television
Two Paraphrases Prediction: midfielder
Three Paraphrases Prediction: midfielder
Four Paraphrases Prediction: midfielder
Five Paraphrases Prediction: maintenance

===
Answers: ['physics', 'physical', 'physic', 'general physics', 'physical science']
Baseline Prediction: optics
Two Paraphrases Prediction: London
Three Paraphrases Prediction: London
Four Paraphrases Prediction: London
Five Paraphrases Prediction: college

===
Answers: ['Norwegian', 'no', 'Norwegian language']
Baseline Prediction: Danish
Two Paraphrases Prediction: London
Three Paraphrases Prediction: London
Four Paraphrases Prediction: London
Five Paraphrases Prediction: London

===
Answers: ['Florence', 'Firenze', 'Florence, Italy', 'Florence, Tuscany', 'Florencia', 'Florentia', 'Florenz', 'Firenca', 'Florencie', 'Fiuränza', 'Florentzia', 'Firense', 'Firenz', 'Firenzi', 'Florence Municipality']
Baseline Prediction: Florence
Two Paraphrases Prediction: 2011
Three Paraphrases Prediction: London
Four Paraphrases Prediction: London
Five Paraphrases Prediction: London

===
Answers: ['Antarctica', 'Antarctic Selection']
Baseline Prediction: Antarctic
Two Paraphrases Prediction: 2011
Three Paraphrases Prediction: London
Four Paraphrases Prediction: London
Five Paraphrases Prediction: London

===
Answers: ['Turin', 'Torino', 'Turin, Italy']
Baseline Prediction: Italy
Two Paraphrases Prediction: London
Three Paraphrases Prediction: London
Four Paraphrases Prediction: London
Five Paraphrases Prediction: London

===
Answers: ['bishop']
Baseline Prediction: actor
Two Paraphrases Prediction: coaches
Three Paraphrases Prediction: Warner
Four Paraphrases Prediction: acting
Five Paraphrases Prediction: music

===
Answers: ['Boston', 'Boston, Lincolnshire', 'Boston, England']
Baseline Prediction: 1940
Two Paraphrases Prediction: acting
Three Paraphrases Prediction: Microsoft
Four Paraphrases Prediction: Warner
Five Paraphrases Prediction: manager

===
Answers: ['NBC', 'National Broadcasting Company']
Baseline Prediction: March
Two Paraphrases Prediction: Warner
Three Paraphrases Prediction: coaches
Four Paraphrases Prediction: acting
Five Paraphrases Prediction: NASA

===
Answers: ['physics', 'physical', 'physic', 'general physics', 'physical science']
Baseline Prediction: physics
Two Paraphrases Prediction: the
Three Paraphrases Prediction: acting
Four Paraphrases Prediction: Warner
Five Paraphrases Prediction: Microsoft

===
Answers: ['Norwegian', 'no', 'Norwegian language']
Baseline Prediction: runes
Two Paraphrases Prediction: NASA
Three Paraphrases Prediction: career
Four Paraphrases Prediction: career
Five Paraphrases Prediction: manager

===
Answers: ['Florence', 'Firenze', 'Florence, Italy', 'Florence, Tuscany', 'Florencia', 'Florentia', 'Florenz', 'Firenca', 'Florencie', 'Fiuränza', 'Florentzia', 'Firense', 'Firenz', 'Firenzi', 'Florence Municipality']
Baseline Prediction: Florence
Two Paraphrases Prediction: Quechua
Three Paraphrases Prediction: sign
Four Paraphrases Prediction: French
Five Paraphrases Prediction: French

===
Answers: ['Antarctica', 'Antarctic Selection']
Baseline Prediction: Antarctica
Two Paraphrases Prediction: French
Three Paraphrases Prediction: French
Four Paraphrases Prediction: French
Five Paraphrases Prediction: sign

===
Answers: ['Turin', 'Torino', 'Turin, Italy']
Baseline Prediction: 1908
Two Paraphrases Prediction: sign
Three Paraphrases Prediction: French
Four Paraphrases Prediction: Quechua
Five Paraphrases Prediction: Quechua

===
Answers: ['bishop']
Baseline Prediction: actor
Two Paraphrases Prediction: French
Three Paraphrases Prediction: Quechua
Four Paraphrases Prediction: Quechua
Five Paraphrases Prediction: Quechua

===
Answers: ['Boston', 'Boston, Lincolnshire', 'Boston, England']
Baseline Prediction: 1940
Two Paraphrases Prediction: radio